### PR TITLE
bind_plots a potential solution for #100

### PR DESCRIPTION
**Pull request by harell**
Thanks for developing DALEX and its associated packages.

Attached is my contribution to the problem posed in issue #100. 
Given `ggplot` objects, possibly with facet_grid,
When `bind_plots` is called  
Then a gridExtra object is returned with the combined plots

# Examples

```
# Setup -------------------------------------------------------------------
library(magrittr)
data <- mtcars %>% dplyr::mutate(vs = factor(vs, levels = 0:1, labels = c("V-shaped", "straight")))
explainer <- DALEX::explain(model = lm(mpg ~., data),
                            data = data %>% dplyr::select(-mpg),
                            y = data %>% dplyr::select(mpg) %>% unlist())

# Generate ggplot objects -------------------------------------------------
ggplot_numerical <- ingredients::partial_dependency(explainer, variable_type = "numerical") %>% plot()
ggplot_categorical <- ingredients::partial_dependency(explainer, variable_type = "categorical") %>% plot()
```

* `ggplot_numerical` is a 3x3 facet grid
* `ggplot_categorical ` is a 1x1 facet grid

# Bind plots by row results with 4x3 facet grid

```
bind_plots(ggplot_numerical, ggplot_categorical, byrow = TRUE)
```

image

# Bind plots by col results with 3x4 facet grid

```
bind_plots(ggplot_numerical, ggplot_categorical, byrow = FALSE)
```

image

### CODE REVIEW

**Review by pbiecek — COMMENTED** [review]
Thanks, this is a useful fix.
What about removing magrittr package from dependencies?
The less dependencies the easier is the maintenance.
IMHO we can easily replace `%>%` by standard function calls.

**Comment by harell** [comment]
Could do. 

This solution import two functions from `magrittr`: __%>\%__ and **extract2**

Notice `ingredients` depend on `ggplot2` which is depended on `rlang` which is depended on `magrittr`. That means, `magrittr` is required in any case.

The main advantage of using **%>%** is making the code more readable and therefore maintainable.

For example:
```
extract_facets <- function(p) p %>% ggplot_build() %>% extract2('layout') %>% extract2('layout')
```

becomes

```
extract_facets <- function(p) extract2(extract2(ggplot_build(p), 'layout') , 'layout')
```

What are your thoughts?

**Comment by pbiecek** [comment]
I have not noticed that ggplot2 also imports magrittr. Good to know.

I have mixed feeling about using %>% in packages, because they are harder to debug.
Single line pipes are short and nice for exploration, but for maintaining they are sometimes harder to follow than 5 separate lines. 
Thank you for this submission. I will sit on this on Friday.

**Comment by pbiecek** [comment]
It looks like the version without magrittr is shorter and easier to read, 
e.g.
```
extract_facets <- function(p) p %>% ggplot_build() %>% extract2('layout') %>% extract2('layout')
```

becomes
```
extract_facets <- function(p) ggplot_build(p)[['layout']][['layout']]
```

**Comment by pbiecek** [comment]
Thanks!

**Pull request merged**
