### PR TITLE
added title to Partial Dependence profile / Accumulated Dependence profile #97

### PR DESCRIPTION
**Pull request by jakwisn**

### CODE REVIEW

**Comment by jakwisn** [comment]
Issue #97

**Comment by pbiecek** [comment]
Thank you.
Can you please expose the `title` and `subtitle` as arguments of the `plot.aggregated_profiles_explainer()` function. 
So the signature will be 
```
plot.aggregated_profiles_explainer(... ..., title = "default value...", subtitle = "default value...")
```
This way the code will be more elastic.

**Review by pbiecek — COMMENTED** [review]
Thank you.
Can you please expose the `title` and `subtitle` as arguments of the `plot.aggregated_profiles_explainer()` function. 
So the signature will be 
```
plot.aggregated_profiles_explainer(... ..., title = "default value...", subtitle = "default value...")
```
This way the code will be more elastic.

**Comment by jakwisn** [comment]
I am sorry, but right now I am away for winter break. I will do it as soon as i am back from my holidays, so unfortunately not untill next Saturday/Sunday. I hope it is not to late.

**Comment by pbiecek** [comment]
no problem, let me know once it is completed

**Review by pbiecek — COMMENTED** [review]
Please correct following problems:

- if possible do not use absolute indexes (never). Instead of `class(x)[2]` it is much safer to use `%in%`
- update Rd files (with `devtools`)
- add unit tests for the proposed changes
- do not use `1:length()` as this will break with zero length vectors. It is much safer to use `seq_along()`

**Comment by Yue-Jiang** [comment]
# [Codecov](https://codecov.io/gh/ModelOriented/ingredients/pull/104?src=pr&el=h1) Report
> Merging [#104](https://codecov.io/gh/ModelOriented/ingredients/pull/104?src=pr&el=desc) into [master](https://codecov.io/gh/ModelOriented/ingredients/commit/65002109a99031e3ec0fd4bf7ed50e4ba28cae19&el=desc) will **decrease** coverage by `0.04%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/ModelOriented/ingredients/pull/104?src=pr&el=tree)

```diff
@@            Coverage Diff             @@
##           master     #104      +/-   ##
==========================================
- Coverage   83.96%   83.91%   -0.05%     
==========================================
  Files          31       32       +1     
  Lines        1434     1480      +46     
==========================================
+ Hits         1204     1242      +38     
- Misses        230      238       +8     
```


| [Impacted Files](https://codecov.io/gh/ModelOriented/ingredients/pull/104?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [R/accumulated\_dependency.R](https://codecov.io/gh/ModelOriented/ingredients/pull/104/diff?src=pr&el=tree#diff-Ui9hY2N1bXVsYXRlZF9kZXBlbmRlbmN5LlI=) | | |
| [R/conditional\_dependency.R](https://codecov.io/gh/ModelOriented/ingredients/pull/104/diff?src=pr&el=tree#diff-Ui9jb25kaXRpb25hbF9kZXBlbmRlbmN5LlI=) | | |
| [R/partial\_dependency.R](https://codecov.io/gh/ModelOriented/ingredients/pull/104/diff?src=pr&el=tree#diff-Ui9wYXJ0aWFsX2RlcGVuZGVuY3kuUg==) | | |
| [R/accumulated\_dependence.R](https://codecov.io/gh/ModelOriented/ingredients/pull/104/diff?src=pr&el=tree#diff-Ui9hY2N1bXVsYXRlZF9kZXBlbmRlbmNlLlI=) | `92.85% <0.00%> (ø)` | |
| [R/conditional\_dependence.R](https://codecov.io/gh/ModelOriented/ingredients/pull/104/diff?src=pr&el=tree#diff-Ui9jb25kaXRpb25hbF9kZXBlbmRlbmNlLlI=) | `96.42% <0.00%> (ø)` | |
| [R/partial\_dependence.R](https://codecov.io/gh/ModelOriented/ingredients/pull/104/diff?src=pr&el=tree#diff-Ui9wYXJ0aWFsX2RlcGVuZGVuY2UuUg==) | `96.42% <0.00%> (ø)` | |
| [R/bind\_plots.R](https://codecov.io/gh/ModelOriented/ingredients/pull/104/diff?src=pr&el=tree#diff-Ui9iaW5kX3Bsb3RzLlI=) | `100.00% <0.00%> (ø)` | |
| [R/describe\_feature\_importance.R](https://codecov.io/gh/ModelOriented/ingredients/pull/104/diff?src=pr&el=tree#diff-Ui9kZXNjcmliZV9mZWF0dXJlX2ltcG9ydGFuY2UuUg==) | `95.45% <0.00%> (+0.21%)` | :arrow_up: |
| [R/plot\_feature\_importance.R](https://codecov.io/gh/ModelOriented/ingredients/pull/104/diff?src=pr&el=tree#diff-Ui9wbG90X2ZlYXR1cmVfaW1wb3J0YW5jZS5S) | `96.00% <0.00%> (+0.44%)` | :arrow_up: |
| [R/show\_aggregated\_profiles.R](https://codecov.io/gh/ModelOriented/ingredients/pull/104/diff?src=pr&el=tree#diff-Ui9zaG93X2FnZ3JlZ2F0ZWRfcHJvZmlsZXMuUg==) | `85.71% <0.00%> (+1.09%)` | :arrow_up: |

------

[Continue to review full report at Codecov](https://codecov.io/gh/ModelOriented/ingredients/pull/104?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/ModelOriented/ingredients/pull/104?src=pr&el=footer). Last update [6500210...b902268](https://codecov.io/gh/ModelOriented/ingredients/pull/104?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by jakwisn** [comment]
Don't know why the test don't pass. Locally everything is ok. Can't spot the mistake

**Comment by Yue-Jiang** [comment]
# [Codecov](https://codecov.io/gh/ModelOriented/ingredients/pull/104?src=pr&el=h1) Report
> Merging [#104](https://codecov.io/gh/ModelOriented/ingredients/pull/104?src=pr&el=desc) into [master](https://codecov.io/gh/ModelOriented/ingredients/commit/b614fe5ed990cab5f53ae6b6db7f2fecc7c26793&el=desc) will **increase** coverage by `0.21%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/ModelOriented/ingredients/pull/104?src=pr&el=tree)

```diff
@@            Coverage Diff             @@
##           master     #104      +/-   ##
==========================================
+ Coverage   84.31%   84.52%   +0.21%     
==========================================
  Files          32       32              
  Lines        1466     1480      +14     
==========================================
+ Hits         1236     1251      +15     
+ Misses        230      229       -1     
```


| [Impacted Files](https://codecov.io/gh/ModelOriented/ingredients/pull/104?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [R/accumulated\_dependence.R](https://codecov.io/gh/ModelOriented/ingredients/pull/104/diff?src=pr&el=tree#diff-Ui9hY2N1bXVsYXRlZF9kZXBlbmRlbmNlLlI=) | `96.42% <0.00%> (+3.57%)` | :arrow_up: |

------

[Continue to review full report at Codecov](https://codecov.io/gh/ModelOriented/ingredients/pull/104?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/ModelOriented/ingredients/pull/104?src=pr&el=footer). Last update [b614fe5...fc5ffc7](https://codecov.io/gh/ModelOriented/ingredients/pull/104?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Pull request merged**
