### PR TITLE
add default title to variable importance plot

### PR DESCRIPTION
**Pull request by pawel99k**
Issue #98

### CODE REVIEW

**Comment by pbiecek** [comment]
Thank you.
Can you please expose the `title` and `subtitle` as arguments of the `plot.variable_importance()` function. 
So the signature will be 
```
plot.feature_importance_explainer(... ..., title = "default value...", subtitle = "default value...")
```
This way the code will be more elastic.

**Review by pbiecek — COMMENTED** [review]
Thank you.
Can you please expose the `title` and `subtitle` as arguments of the `plot.variable_importance()` function. 
So the signature will be 
```
plot.feature_importance_explainer(... ..., title = "default value...", subtitle = "default value...")
```
This way the code will be more elastic.

**Comment by pawel99k** [comment]
Unfortunately, I am spending my weekend outside my home but, of course, I can edit it on Monday. Should I change the man documentation as well? Am I supposed to come to the office next week?

**Comment by Yue-Jiang** [comment]
# [Codecov](https://codecov.io/gh/ModelOriented/ingredients/pull/102?src=pr&el=h1) Report
> Merging [#102](https://codecov.io/gh/ModelOriented/ingredients/pull/102?src=pr&el=desc) into [master](https://codecov.io/gh/ModelOriented/ingredients/commit/1990068326b3d61cf5c5145c25af6f3e4941848e&el=desc) will **increase** coverage by `0.05%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/ModelOriented/ingredients/pull/102?src=pr&el=tree)

```diff
@@            Coverage Diff             @@
##           master     #102      +/-   ##
==========================================
+ Coverage   84.25%   84.31%   +0.05%     
==========================================
  Files          32       32              
  Lines        1461     1466       +5     
==========================================
+ Hits         1231     1236       +5     
  Misses        230      230              
```



------

[Continue to review full report at Codecov](https://codecov.io/gh/ModelOriented/ingredients/pull/102?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/ModelOriented/ingredients/pull/102?src=pr&el=footer). Last update [1990068...b2a0457](https://codecov.io/gh/ModelOriented/ingredients/pull/102?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Pull request merged**
